apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: psd
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - port: 4002
      targetPort: 4002
      protocol: TCP
