apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  namespace: psd
spec:
  type: ClusterIP
  selector:
    app: feedback-service
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
