drop extension if exists "pg_net";

create type "public"."app_role" as enum ('superadmin', 'admin');

create sequence "public"."events_id_seq";


  create table "public"."answers" (
    "id" bigint generated by default as identity not null,
    "response_id" bigint not null,
    "question_id" bigint not null,
    "option_id" bigint,
    "answer_text" text,
    "answer_numeric" integer,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."answers" enable row level security;


  create table "public"."booth_completions" (
    "id" bigint generated by default as identity not null,
    "event_id" bigint not null,
    "quest_id" bigint not null,
    "visitor_id" text not null,
    "completed_at" timestamp with time zone not null default now(),
    "method" text not null default 'pin'::text
      );


alter table "public"."booth_completions" enable row level security;


  create table "public"."event_admins" (
    "event_id" bigint not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."event_admins" enable row level security;


  create table "public"."event_device_entries" (
    "id" bigint generated by default as identity not null,
    "event_id" bigint not null,
    "visitor_id" text not null,
    "first_seen_at" timestamp with time zone not null default now(),
    "source" text,
    "lang" text,
    "user_agent_hash" text
      );


alter table "public"."event_device_entries" enable row level security;


  create table "public"."events" (
    "id" bigint not null default nextval('public.events_id_seq'::regclass),
    "name" text not null,
    "location" text,
    "start_date" date,
    "end_date" date,
    "created_at" timestamp with time zone not null default now(),
    "is_active" boolean not null default false,
    "story_mode_enabled" boolean not null default true
      );


alter table "public"."events" enable row level security;


  create table "public"."quest" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_id" bigint,
    "title" character varying,
    "description" character varying,
    "is_active" boolean,
    "pin" text
      );


alter table "public"."quest" enable row level security;


  create table "public"."question_options" (
    "id" bigint generated by default as identity not null,
    "question_id" bigint not null,
    "option_text" text not null,
    "sort_order" integer default 0,
    "created_at" timestamp with time zone default now(),
    "choice_key" text
      );


alter table "public"."question_options" enable row level security;


  create table "public"."questions" (
    "id" bigint generated by default as identity not null,
    "question_text" text not null,
    "question_type" text not null,
    "category" text,
    "sort_order" integer default 0,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "event_id" bigint not null,
    "dialogue_1_name" text default 'Cell A'::text,
    "dialogue_1_avatar_url" text default '/images/cell1-head.png'::text,
    "dialogue_2_name" text not null default 'Cell B'::text,
    "dialogue_2_avatar_url" text not null default '/images/cell2-head.png'::text,
    "question_tab_name" text default 'Guardian'::text,
    "question_tab_avatar_url" text default '/images/guardian-head.png'::text
      );


alter table "public"."questions" enable row level security;


  create table "public"."responses" (
    "id" bigint generated by default as identity not null,
    "event_id" bigint not null,
    "submitted_at" timestamp with time zone default now()
      );


alter table "public"."responses" enable row level security;


  create table "public"."social_items" (
    "id" bigint generated always as identity not null,
    "section_id" bigint not null,
    "title" text not null,
    "detail" text,
    "url" text not null
      );



  create table "public"."social_sections" (
    "id" bigint generated always as identity not null,
    "title" text not null,
    "display_order" integer not null default 0
      );



  create table "public"."superadmin_emails" (
    "email" text not null
      );


alter table "public"."superadmin_emails" enable row level security;


  create table "public"."user_roles" (
    "user_id" uuid not null,
    "role" public.app_role not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."user_roles" enable row level security;

alter sequence "public"."events_id_seq" owned by "public"."events"."id";

CREATE UNIQUE INDEX answers_pkey ON public.answers USING btree (id);

CREATE INDEX booth_completions_completed_at_idx ON public.booth_completions USING btree (completed_at DESC);

CREATE INDEX booth_completions_event_id_idx ON public.booth_completions USING btree (event_id);

CREATE INDEX booth_completions_event_quest_idx ON public.booth_completions USING btree (event_id, quest_id);

CREATE UNIQUE INDEX booth_completions_event_quest_visitor_unique ON public.booth_completions USING btree (event_id, quest_id, visitor_id);

CREATE UNIQUE INDEX booth_completions_pkey ON public.booth_completions USING btree (id);

CREATE INDEX event_admins_event_idx ON public.event_admins USING btree (event_id);

CREATE UNIQUE INDEX event_admins_pkey ON public.event_admins USING btree (event_id, user_id);

CREATE INDEX event_admins_user_idx ON public.event_admins USING btree (user_id);

CREATE INDEX event_device_entries_event_id_idx ON public.event_device_entries USING btree (event_id);

CREATE UNIQUE INDEX event_device_entries_event_visitor_unique ON public.event_device_entries USING btree (event_id, visitor_id);

CREATE INDEX event_device_entries_first_seen_at_idx ON public.event_device_entries USING btree (first_seen_at DESC);

CREATE UNIQUE INDEX event_device_entries_pkey ON public.event_device_entries USING btree (id);

CREATE INDEX event_device_entries_visitor_id_idx ON public.event_device_entries USING btree (visitor_id);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE INDEX idx_answers_question ON public.answers USING btree (question_id);

CREATE INDEX idx_answers_question_option ON public.answers USING btree (question_id, option_id);

CREATE INDEX idx_events_is_active_start_date ON public.events USING btree (is_active, start_date);

CREATE INDEX idx_question_options_question ON public.question_options USING btree (question_id);

CREATE INDEX idx_questions_event_active_sort ON public.questions USING btree (event_id, is_active, sort_order);

CREATE INDEX idx_responses_event_submitted_at ON public.responses USING btree (event_id, submitted_at);

CREATE UNIQUE INDEX quest_pkey ON public.quest USING btree (id);

CREATE UNIQUE INDEX question_options_pkey ON public.question_options USING btree (id);

CREATE UNIQUE INDEX questions_pkey ON public.questions USING btree (id);

CREATE UNIQUE INDEX responses_pkey ON public.responses USING btree (id);

CREATE UNIQUE INDEX social_items_pkey ON public.social_items USING btree (id);

CREATE UNIQUE INDEX social_sections_pkey ON public.social_sections USING btree (id);

CREATE UNIQUE INDEX superadmin_emails_pkey ON public.superadmin_emails USING btree (email);

CREATE UNIQUE INDEX uq_answers_response_question ON public.answers USING btree (response_id, question_id);

CREATE UNIQUE INDEX uq_question_options_question_choice ON public.question_options USING btree (question_id, choice_key) WHERE (choice_key IS NOT NULL);

CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (user_id);

alter table "public"."answers" add constraint "answers_pkey" PRIMARY KEY using index "answers_pkey";

alter table "public"."booth_completions" add constraint "booth_completions_pkey" PRIMARY KEY using index "booth_completions_pkey";

alter table "public"."event_admins" add constraint "event_admins_pkey" PRIMARY KEY using index "event_admins_pkey";

alter table "public"."event_device_entries" add constraint "event_device_entries_pkey" PRIMARY KEY using index "event_device_entries_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."quest" add constraint "quest_pkey" PRIMARY KEY using index "quest_pkey";

alter table "public"."question_options" add constraint "question_options_pkey" PRIMARY KEY using index "question_options_pkey";

alter table "public"."questions" add constraint "questions_pkey" PRIMARY KEY using index "questions_pkey";

alter table "public"."responses" add constraint "responses_pkey" PRIMARY KEY using index "responses_pkey";

alter table "public"."social_items" add constraint "social_items_pkey" PRIMARY KEY using index "social_items_pkey";

alter table "public"."social_sections" add constraint "social_sections_pkey" PRIMARY KEY using index "social_sections_pkey";

alter table "public"."superadmin_emails" add constraint "superadmin_emails_pkey" PRIMARY KEY using index "superadmin_emails_pkey";

alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";

alter table "public"."answers" add constraint "answers_option_id_fkey" FOREIGN KEY (option_id) REFERENCES public.question_options(id) ON DELETE CASCADE not valid;

alter table "public"."answers" validate constraint "answers_option_id_fkey";

alter table "public"."answers" add constraint "answers_question_id_fkey" FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE not valid;

alter table "public"."answers" validate constraint "answers_question_id_fkey";

alter table "public"."answers" add constraint "answers_response_id_fkey" FOREIGN KEY (response_id) REFERENCES public.responses(id) ON DELETE CASCADE not valid;

alter table "public"."answers" validate constraint "answers_response_id_fkey";

alter table "public"."booth_completions" add constraint "booth_completions_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE not valid;

alter table "public"."booth_completions" validate constraint "booth_completions_event_id_fkey";

alter table "public"."booth_completions" add constraint "booth_completions_event_quest_visitor_unique" UNIQUE using index "booth_completions_event_quest_visitor_unique";

alter table "public"."booth_completions" add constraint "booth_completions_method_check" CHECK ((method = 'pin'::text)) not valid;

alter table "public"."booth_completions" validate constraint "booth_completions_method_check";

alter table "public"."booth_completions" add constraint "booth_completions_quest_id_fkey" FOREIGN KEY (quest_id) REFERENCES public.quest(id) ON DELETE CASCADE not valid;

alter table "public"."booth_completions" validate constraint "booth_completions_quest_id_fkey";

alter table "public"."event_admins" add constraint "event_admins_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE not valid;

alter table "public"."event_admins" validate constraint "event_admins_event_id_fkey";

alter table "public"."event_admins" add constraint "event_admins_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."event_admins" validate constraint "event_admins_user_id_fkey";

alter table "public"."event_device_entries" add constraint "event_device_entries_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE not valid;

alter table "public"."event_device_entries" validate constraint "event_device_entries_event_id_fkey";

alter table "public"."event_device_entries" add constraint "event_device_entries_event_visitor_unique" UNIQUE using index "event_device_entries_event_visitor_unique";

alter table "public"."quest" add constraint "quest_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE not valid;

alter table "public"."quest" validate constraint "quest_event_id_fkey";

alter table "public"."question_options" add constraint "question_options_choice_key_check" CHECK ((choice_key = ANY (ARRAY['A'::text, 'B'::text]))) not valid;

alter table "public"."question_options" validate constraint "question_options_choice_key_check";

alter table "public"."question_options" add constraint "question_options_question_id_fkey" FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE not valid;

alter table "public"."question_options" validate constraint "question_options_question_id_fkey";

alter table "public"."questions" add constraint "questions_event_fk" FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE not valid;

alter table "public"."questions" validate constraint "questions_event_fk";

alter table "public"."questions" add constraint "questions_question_type_check" CHECK ((question_type = ANY (ARRAY['text'::text, 'rating'::text, 'yes_no'::text, 'mcq'::text]))) not valid;

alter table "public"."questions" validate constraint "questions_question_type_check";

alter table "public"."responses" add constraint "responses_event_fk" FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE not valid;

alter table "public"."responses" validate constraint "responses_event_fk";

alter table "public"."social_items" add constraint "social_items_section_id_fkey" FOREIGN KEY (section_id) REFERENCES public.social_sections(id) ON DELETE CASCADE not valid;

alter table "public"."social_items" validate constraint "social_items_section_id_fkey";

alter table "public"."user_roles" add constraint "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_roles" validate constraint "user_roles_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.assign_admin_by_email(p_email text, p_event_ids bigint[])
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_user_id uuid;
  v_event_id bigint;
begin
  if not public.is_superadmin() then
    raise exception 'Only superadmin can assign admins';
  end if;

  select id into v_user_id
  from auth.users
  where lower(email) = lower(trim(p_email))
  limit 1;

  if v_user_id is null then
    raise exception 'User not found for email %', p_email;
  end if;

  insert into public.user_roles(user_id, role)
  values (v_user_id, 'admin')
  on conflict (user_id) do update set role = 'admin';

  foreach v_event_id in array p_event_ids
  loop
    insert into public.event_admins(event_id, user_id)
    values (v_event_id, v_user_id)
    on conflict do nothing;
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.assign_initial_role()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  -- If signup email is allowlisted, assign superadmin role
  if exists (
    select 1
    from public.superadmin_emails s
    where lower(s.email) = lower(new.email)
  ) then
    insert into public.user_roles(user_id, role)
    values (new.id, 'superadmin')
    on conflict (user_id) do update set role = excluded.role;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.can_manage_event(target_event_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select
    public.is_superadmin()
    or exists (
      select 1
      from public.event_admins ea
      where ea.event_id = target_event_id
        and ea.user_id = auth.uid()
    );
$function$
;

CREATE OR REPLACE FUNCTION public.enforce_answer_event_match()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if (select event_id from questions where id = new.question_id) <>
     (select event_id from responses where id = new.response_id) then
    raise exception 'answers.question_id must belong to the same event as responses.event_id';
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.enforce_response_event_match()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  response_event_id bigint;
  question_event_id bigint;
begin
  select event_id into response_event_id
  from responses
  where id = new.response_id;

  select event_id into question_event_id
  from questions
  where id = new.question_id;

  if response_event_id is null or question_event_id is null then
    raise exception 'Invalid response_id or question_id';
  end if;

  if response_event_id <> question_event_id then
    raise exception 'Response/event mismatch';
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_feedback_questions_atomic(p_event_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  v_questions jsonb;
begin
  if p_event_id is null or p_event_id <= 0 then
    raise exception using
      message = 'Invalid event id for feedback question loading.',
      detail = 'Expected a positive event id.',
      hint = 'Provide a valid event id before calling get_feedback_questions_atomic.';
  end if;

  if exists (
    select 1
    from questions q
    where q.event_id = p_event_id
      and q.is_active = true
      and not exists (
        select 1
        from question_options qo
        where qo.question_id = q.id
      )
  ) then
    raise exception using
      message = 'Atomic feedback load failed: one or more active questions are missing options.',
      detail = format('event_id=%s', p_event_id),
      hint = 'Ensure every active question has at least one option before loading feedback.';
  end if;

  select
    coalesce(
      jsonb_agg(
        question_row
        order by question_sort_order nulls last, question_created_at asc, question_id asc
      ),
      '[]'::jsonb
    )
  into v_questions
  from (
    select
      q.id as question_id,
      q.sort_order as question_sort_order,
      q.created_at as question_created_at,
      jsonb_build_object(
        'id', q.id,
        'event_id', q.event_id,
        'question_text', q.question_text,
        'question_type', q.question_type,
        'dialogue_1_text', null,
        'dialogue_1_name', q.dialogue_1_name,
        'dialogue_1_avatar_url', q.dialogue_1_avatar_url,
        'dialogue_2_text', null,
        'dialogue_2_name', q.dialogue_2_name,
        'dialogue_2_avatar_url', q.dialogue_2_avatar_url,
        'question_tab_name', q.question_tab_name,
        'question_tab_avatar_url', q.question_tab_avatar_url,
        'sort_order', q.sort_order,
        'is_active', q.is_active,
        'created_at', q.created_at,
        'options', coalesce(
          (
            select
              jsonb_agg(
                jsonb_build_object(
                  'id', qo.id,
                  'question_id', qo.question_id,
                  'option_text', qo.option_text,
                  'sort_order', qo.sort_order,
                  'choice_key', qo.choice_key,
                  'created_at', qo.created_at
                )
                order by qo.sort_order nulls last, qo.created_at asc, qo.id asc
              )
            from question_options qo
            where qo.question_id = q.id
          ),
          '[]'::jsonb
        )
      ) as question_row
    from questions q
    where q.event_id = p_event_id
      and q.is_active = true
  ) prepared_rows;

  return v_questions;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select ur.role::text
  from public.user_roles ur
  where ur.user_id = auth.uid()
  limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.is_superadmin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid()
      and ur.role = 'superadmin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.list_assignable_admin_users()
 RETURNS TABLE(email text)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select lower(u.email)::text as email
  from auth.users u
  where u.email is not null
    and not exists (
      select 1
      from public.user_roles ur
      where ur.user_id = u.id
        and ur.role = 'superadmin'
    )
  order by 1;
$function$
;

CREATE OR REPLACE FUNCTION public.set_event_story_mode(p_event_id bigint, p_story_mode_enabled boolean)
 RETURNS TABLE(id bigint, story_mode_enabled boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  declare
    v_user_id uuid;
    v_role text;
  begin
    v_user_id := auth.uid();

    if v_user_id is null then
      raise exception 'Not authenticated';
    end if;

    select ur.role::text
    into v_role
    from public.user_roles ur
    where ur.user_id = v_user_id
    limit 1;

    if v_role is distinct from 'superadmin' then
      raise exception 'Only superadmin can update story mode';
    end if;

    return query
    update public.events e
    set story_mode_enabled = p_story_mode_enabled
    where e.id = p_event_id
    returning e.id, e.story_mode_enabled;
  end;
  $function$
;

CREATE OR REPLACE FUNCTION public.submit_feedback(p_event_id bigint, p_answers jsonb, p_submitted_at timestamp with time zone DEFAULT now())
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_response_id bigint;
  v_inserted_count integer;
  v_input_count integer;
begin
  if jsonb_typeof(p_answers) <> 'array' then
    raise exception 'p_answers must be a JSON array';
  end if;
  
  if not exists (select 1 from public.events where id = p_event_id) then
    raise exception 'Event % does not exist', p_event_id;
  end if;
  
  if jsonb_array_length(p_answers) = 0 then
    raise exception 'Cannot submit empty feedback';
  end if;

  -- Count input answers early
  v_input_count := jsonb_array_length(p_answers);

  -- Reject duplicate question_id entries
  if exists (
    with parsed_ids as (
      select (x.data->>'question_id')::bigint as question_id
      from jsonb_array_elements(p_answers) as x(data)
      where x.data->>'question_id' is not null
    )
    select 1
    from parsed_ids
    group by question_id
    having count(*) > 1
  ) then
    raise exception 'Duplicate question_id values are not allowed';
  end if;

  insert into public.responses (event_id, submitted_at)
  values (p_event_id, p_submitted_at)
  returning id into v_response_id;
  
  with parsed as (
    select
      (x.data->>'question_id')::bigint as question_id,
      nullif(x.data->>'option_id', '')::bigint as option_id,
      nullif(x.data->>'answer_text', '') as answer_text,
      nullif(x.data->>'answer_numeric', '')::integer as answer_numeric,
      coalesce(nullif(x.data->>'created_at', '')::timestamptz, p_submitted_at) as created_at
    from jsonb_array_elements(p_answers) as x(data)
  ),
  validated as (
    select p.*
    from parsed p
    join public.questions q
      on q.id = p.question_id
     and q.event_id = p_event_id
    left join public.question_options qo
      on qo.id = p.option_id
     and qo.question_id = p.question_id
    where p.question_id is not null
      and (p.option_id is null or qo.id is not null)
  )
  insert into public.answers (
    response_id, question_id, option_id, answer_text, answer_numeric, created_at
  )
  select
    v_response_id,
    question_id,
    option_id,
    answer_text,
    answer_numeric,
    created_at
  from validated;
  
  get diagnostics v_inserted_count = row_count;
  
  -- Fail if any answers were rejected
  if v_inserted_count <> v_input_count then
    raise exception 'Invalid answers detected: % provided, only % valid. All answers must be valid for event %', 
      v_input_count, v_inserted_count, p_event_id;
  end if;
  
  if v_inserted_count = 0 then
    raise exception 'No valid answers provided for event %', p_event_id;
  end if;
  
  return v_response_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_question_with_options_atomic(p_question_id bigint, p_question_text text, p_question_type text, p_options jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_trimmed_question_text text;
  v_trimmed_question_type text;
  v_option_count integer;
  v_empty_option_count integer;
  v_invalid_choice_count integer;
  v_duplicate_choice_count integer;
  v_duplicate_sort_count integer;
  v_invalid_option_id_count integer;
  v_duplicate_option_id_count integer;
  v_existing_option_ids bigint[];
  v_inserted_option_ids bigint[];
  v_keep_option_ids bigint[];
  v_question_row questions%rowtype;
begin
  if p_question_id is null or p_question_id <= 0 then
    raise exception using
      message = 'Invalid question id.',
      detail = 'p_question_id must be a positive integer.';
  end if;

  v_trimmed_question_text := btrim(coalesce(p_question_text, ''));
  if v_trimmed_question_text = '' then
    raise exception using
      message = 'Question text cannot be empty.';
  end if;

  v_trimmed_question_type := btrim(coalesce(p_question_type, ''));
  if v_trimmed_question_type = '' then
    raise exception using
      message = 'Question type cannot be empty.';
  end if;

  if v_trimmed_question_type not in ('text', 'rating', 'yes_no', 'mcq') then
    raise exception using
      message = format('Invalid question type: %s', v_trimmed_question_type),
      hint = 'Use one of: text, rating, yes_no, mcq.';
  end if;

  if p_options is null or jsonb_typeof(p_options) <> 'array' then
    raise exception using
      message = 'Options payload must be a JSON array.';
  end if;

  select count(*)
  into v_option_count
  from jsonb_array_elements(p_options);

  if v_option_count <> 2 then
    raise exception using
      message = 'Exactly 2 options are required.',
      detail = format('Received %s option(s).', v_option_count),
      hint = 'Provide one option for Cell A and one option for Cell B.';
  end if;

  with parsed_options as (
    select
      case
        when coalesce(item.value->>'id', '') ~ '^[0-9]+$' then (item.value->>'id')::bigint
        else null
      end as id,
      btrim(coalesce(item.value->>'option_text', '')) as option_text,
      upper(btrim(coalesce(item.value->>'choice_key', ''))) as choice_key,
      case
        when coalesce(item.value->>'sort_order', '') ~ '^-?[0-9]+$' then (item.value->>'sort_order')::integer
        else item.ordinality::integer - 1
      end as sort_order
    from jsonb_array_elements(p_options) with ordinality as item(value, ordinality)
  )
  select count(*)
  into v_empty_option_count
  from parsed_options
  where option_text = '';

  if v_empty_option_count > 0 then
    raise exception using
      message = 'Option text cannot be empty.';
  end if;

  with parsed_options as (
    select
      upper(btrim(coalesce(item.value->>'choice_key', ''))) as choice_key
    from jsonb_array_elements(p_options) with ordinality as item(value, ordinality)
  )
  select count(*)
  into v_invalid_choice_count
  from parsed_options
  where choice_key not in ('A', 'B');

  if v_invalid_choice_count > 0 then
    raise exception using
      message = 'Each option must be assigned to A or B.';
  end if;

  with parsed_options as (
    select
      upper(btrim(coalesce(item.value->>'choice_key', ''))) as choice_key
    from jsonb_array_elements(p_options) with ordinality as item(value, ordinality)
  ),
  duplicate_choices as (
    select choice_key
    from parsed_options
    group by choice_key
    having count(*) > 1
  )
  select count(*)
  into v_duplicate_choice_count
  from duplicate_choices;

  if v_duplicate_choice_count > 0 then
    raise exception using
      message = 'Options must have unique A and B assignments.';
  end if;

  with parsed_options as (
    select
      case
        when coalesce(item.value->>'sort_order', '') ~ '^-?[0-9]+$' then (item.value->>'sort_order')::integer
        else item.ordinality::integer - 1
      end as sort_order
    from jsonb_array_elements(p_options) with ordinality as item(value, ordinality)
  ),
  duplicate_sort_orders as (
    select sort_order
    from parsed_options
    group by sort_order
    having count(*) > 1
  )
  select count(*)
  into v_duplicate_sort_count
  from duplicate_sort_orders;

  if v_duplicate_sort_count > 0 then
    raise exception using
      message = 'Option order contains duplicates.';
  end if;

  with parsed_options as (
    select
      case
        when coalesce(item.value->>'id', '') ~ '^[0-9]+$' then (item.value->>'id')::bigint
        else null
      end as id
    from jsonb_array_elements(p_options) with ordinality as item(value, ordinality)
  )
  select count(*)
  into v_invalid_option_id_count
  from parsed_options p
  where p.id is not null
    and not exists (
      select 1
      from question_options qo
      where qo.id = p.id
        and qo.question_id = p_question_id
    );

  if v_invalid_option_id_count > 0 then
    raise exception using
      message = 'One or more option ids do not belong to this question.';
  end if;

  with parsed_options as (
    select
      case
        when coalesce(item.value->>'id', '') ~ '^[0-9]+$' then (item.value->>'id')::bigint
        else null
      end as id
    from jsonb_array_elements(p_options) with ordinality as item(value, ordinality)
  ),
  duplicate_ids as (
    select id
    from parsed_options
    where id is not null
    group by id
    having count(*) > 1
  )
  select count(*)
  into v_duplicate_option_id_count
  from duplicate_ids;

  if v_duplicate_option_id_count > 0 then
    raise exception using
      message = 'Duplicate option ids were provided in the request.';
  end if;

  select *
  into v_question_row
  from questions q
  where q.id = p_question_id
  for update;

  if not found then
    raise exception using
      message = 'Question not found.',
      detail = format('question_id=%s', p_question_id);
  end if;

  update questions
  set
    question_text = v_trimmed_question_text,
    question_type = v_trimmed_question_type
  where id = p_question_id
  returning *
  into v_question_row;

  with parsed_options as (
    select
      case
        when coalesce(item.value->>'id', '') ~ '^[0-9]+$' then (item.value->>'id')::bigint
        else null
      end as id,
      btrim(coalesce(item.value->>'option_text', '')) as option_text,
      upper(btrim(coalesce(item.value->>'choice_key', ''))) as choice_key,
      case
        when coalesce(item.value->>'sort_order', '') ~ '^-?[0-9]+$' then (item.value->>'sort_order')::integer
        else item.ordinality::integer - 1
      end as sort_order
    from jsonb_array_elements(p_options) with ordinality as item(value, ordinality)
  )
  update question_options qo
  set
    option_text = p.option_text,
    sort_order = p.sort_order,
    choice_key = p.choice_key
  from parsed_options p
  where p.id is not null
    and qo.id = p.id
    and qo.question_id = p_question_id;

  with parsed_options as (
    select
      case
        when coalesce(item.value->>'id', '') ~ '^[0-9]+$' then (item.value->>'id')::bigint
        else null
      end as id
    from jsonb_array_elements(p_options) with ordinality as item(value, ordinality)
  )
  select coalesce(array_agg(id), '{}'::bigint[])
  into v_existing_option_ids
  from parsed_options
  where id is not null;

  with parsed_options as (
    select
      case
        when coalesce(item.value->>'id', '') ~ '^[0-9]+$' then (item.value->>'id')::bigint
        else null
      end as id,
      btrim(coalesce(item.value->>'option_text', '')) as option_text,
      upper(btrim(coalesce(item.value->>'choice_key', ''))) as choice_key,
      case
        when coalesce(item.value->>'sort_order', '') ~ '^-?[0-9]+$' then (item.value->>'sort_order')::integer
        else item.ordinality::integer - 1
      end as sort_order
    from jsonb_array_elements(p_options) with ordinality as item(value, ordinality)
  ),
  inserted as (
    insert into question_options (question_id, option_text, sort_order, choice_key)
    select
      p_question_id,
      p.option_text,
      p.sort_order,
      p.choice_key
    from parsed_options p
    where p.id is null
    returning id
  )
  select coalesce(array_agg(id), '{}'::bigint[])
  into v_inserted_option_ids
  from inserted;

  v_keep_option_ids := coalesce(v_existing_option_ids, '{}'::bigint[]) || coalesce(v_inserted_option_ids, '{}'::bigint[]);

  delete from question_options qo
  where qo.question_id = p_question_id
    and not (qo.id = any(v_keep_option_ids));

  return jsonb_build_object(
    'question',
    to_jsonb(v_question_row),
    'options',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', qo.id,
            'question_id', qo.question_id,
            'option_text', qo.option_text,
            'sort_order', qo.sort_order,
            'choice_key', qo.choice_key,
            'created_at', qo.created_at
          )
          order by qo.sort_order nulls last, qo.created_at asc, qo.id asc
        )
        from question_options qo
        where qo.question_id = p_question_id
      ),
      '[]'::jsonb
    )
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_booth_completion_event_match()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if not exists (
    select 1
    from public.quest q
    where q.id = new.quest_id
      and q.event_id = new.event_id
  ) then
    raise exception 'quest_id % does not belong to event_id %', new.quest_id, new.event_id;
  end if;

  return new;
end;
$function$
;

grant delete on table "public"."answers" to "anon";

grant insert on table "public"."answers" to "anon";

grant references on table "public"."answers" to "anon";

grant select on table "public"."answers" to "anon";

grant trigger on table "public"."answers" to "anon";

grant truncate on table "public"."answers" to "anon";

grant update on table "public"."answers" to "anon";

grant delete on table "public"."answers" to "authenticated";

grant insert on table "public"."answers" to "authenticated";

grant references on table "public"."answers" to "authenticated";

grant select on table "public"."answers" to "authenticated";

grant trigger on table "public"."answers" to "authenticated";

grant truncate on table "public"."answers" to "authenticated";

grant update on table "public"."answers" to "authenticated";

grant delete on table "public"."answers" to "service_role";

grant insert on table "public"."answers" to "service_role";

grant references on table "public"."answers" to "service_role";

grant select on table "public"."answers" to "service_role";

grant trigger on table "public"."answers" to "service_role";

grant truncate on table "public"."answers" to "service_role";

grant update on table "public"."answers" to "service_role";

grant delete on table "public"."booth_completions" to "anon";

grant insert on table "public"."booth_completions" to "anon";

grant references on table "public"."booth_completions" to "anon";

grant select on table "public"."booth_completions" to "anon";

grant trigger on table "public"."booth_completions" to "anon";

grant truncate on table "public"."booth_completions" to "anon";

grant update on table "public"."booth_completions" to "anon";

grant delete on table "public"."booth_completions" to "authenticated";

grant insert on table "public"."booth_completions" to "authenticated";

grant references on table "public"."booth_completions" to "authenticated";

grant select on table "public"."booth_completions" to "authenticated";

grant trigger on table "public"."booth_completions" to "authenticated";

grant truncate on table "public"."booth_completions" to "authenticated";

grant update on table "public"."booth_completions" to "authenticated";

grant delete on table "public"."booth_completions" to "service_role";

grant insert on table "public"."booth_completions" to "service_role";

grant references on table "public"."booth_completions" to "service_role";

grant select on table "public"."booth_completions" to "service_role";

grant trigger on table "public"."booth_completions" to "service_role";

grant truncate on table "public"."booth_completions" to "service_role";

grant update on table "public"."booth_completions" to "service_role";

grant delete on table "public"."event_admins" to "anon";

grant insert on table "public"."event_admins" to "anon";

grant references on table "public"."event_admins" to "anon";

grant select on table "public"."event_admins" to "anon";

grant trigger on table "public"."event_admins" to "anon";

grant truncate on table "public"."event_admins" to "anon";

grant update on table "public"."event_admins" to "anon";

grant delete on table "public"."event_admins" to "authenticated";

grant insert on table "public"."event_admins" to "authenticated";

grant references on table "public"."event_admins" to "authenticated";

grant select on table "public"."event_admins" to "authenticated";

grant trigger on table "public"."event_admins" to "authenticated";

grant truncate on table "public"."event_admins" to "authenticated";

grant update on table "public"."event_admins" to "authenticated";

grant delete on table "public"."event_admins" to "service_role";

grant insert on table "public"."event_admins" to "service_role";

grant references on table "public"."event_admins" to "service_role";

grant select on table "public"."event_admins" to "service_role";

grant trigger on table "public"."event_admins" to "service_role";

grant truncate on table "public"."event_admins" to "service_role";

grant update on table "public"."event_admins" to "service_role";

grant delete on table "public"."event_device_entries" to "anon";

grant insert on table "public"."event_device_entries" to "anon";

grant references on table "public"."event_device_entries" to "anon";

grant select on table "public"."event_device_entries" to "anon";

grant trigger on table "public"."event_device_entries" to "anon";

grant truncate on table "public"."event_device_entries" to "anon";

grant update on table "public"."event_device_entries" to "anon";

grant delete on table "public"."event_device_entries" to "authenticated";

grant insert on table "public"."event_device_entries" to "authenticated";

grant references on table "public"."event_device_entries" to "authenticated";

grant select on table "public"."event_device_entries" to "authenticated";

grant trigger on table "public"."event_device_entries" to "authenticated";

grant truncate on table "public"."event_device_entries" to "authenticated";

grant update on table "public"."event_device_entries" to "authenticated";

grant delete on table "public"."event_device_entries" to "service_role";

grant insert on table "public"."event_device_entries" to "service_role";

grant references on table "public"."event_device_entries" to "service_role";

grant select on table "public"."event_device_entries" to "service_role";

grant trigger on table "public"."event_device_entries" to "service_role";

grant truncate on table "public"."event_device_entries" to "service_role";

grant update on table "public"."event_device_entries" to "service_role";

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";

grant delete on table "public"."quest" to "anon";

grant insert on table "public"."quest" to "anon";

grant references on table "public"."quest" to "anon";

grant select on table "public"."quest" to "anon";

grant trigger on table "public"."quest" to "anon";

grant truncate on table "public"."quest" to "anon";

grant update on table "public"."quest" to "anon";

grant delete on table "public"."quest" to "authenticated";

grant insert on table "public"."quest" to "authenticated";

grant references on table "public"."quest" to "authenticated";

grant select on table "public"."quest" to "authenticated";

grant trigger on table "public"."quest" to "authenticated";

grant truncate on table "public"."quest" to "authenticated";

grant update on table "public"."quest" to "authenticated";

grant delete on table "public"."quest" to "service_role";

grant insert on table "public"."quest" to "service_role";

grant references on table "public"."quest" to "service_role";

grant select on table "public"."quest" to "service_role";

grant trigger on table "public"."quest" to "service_role";

grant truncate on table "public"."quest" to "service_role";

grant update on table "public"."quest" to "service_role";

grant delete on table "public"."question_options" to "anon";

grant insert on table "public"."question_options" to "anon";

grant references on table "public"."question_options" to "anon";

grant select on table "public"."question_options" to "anon";

grant trigger on table "public"."question_options" to "anon";

grant truncate on table "public"."question_options" to "anon";

grant update on table "public"."question_options" to "anon";

grant delete on table "public"."question_options" to "authenticated";

grant insert on table "public"."question_options" to "authenticated";

grant references on table "public"."question_options" to "authenticated";

grant select on table "public"."question_options" to "authenticated";

grant trigger on table "public"."question_options" to "authenticated";

grant truncate on table "public"."question_options" to "authenticated";

grant update on table "public"."question_options" to "authenticated";

grant delete on table "public"."question_options" to "service_role";

grant insert on table "public"."question_options" to "service_role";

grant references on table "public"."question_options" to "service_role";

grant select on table "public"."question_options" to "service_role";

grant trigger on table "public"."question_options" to "service_role";

grant truncate on table "public"."question_options" to "service_role";

grant update on table "public"."question_options" to "service_role";

grant delete on table "public"."questions" to "anon";

grant insert on table "public"."questions" to "anon";

grant references on table "public"."questions" to "anon";

grant select on table "public"."questions" to "anon";

grant trigger on table "public"."questions" to "anon";

grant truncate on table "public"."questions" to "anon";

grant update on table "public"."questions" to "anon";

grant delete on table "public"."questions" to "authenticated";

grant insert on table "public"."questions" to "authenticated";

grant references on table "public"."questions" to "authenticated";

grant select on table "public"."questions" to "authenticated";

grant trigger on table "public"."questions" to "authenticated";

grant truncate on table "public"."questions" to "authenticated";

grant update on table "public"."questions" to "authenticated";

grant delete on table "public"."questions" to "service_role";

grant insert on table "public"."questions" to "service_role";

grant references on table "public"."questions" to "service_role";

grant select on table "public"."questions" to "service_role";

grant trigger on table "public"."questions" to "service_role";

grant truncate on table "public"."questions" to "service_role";

grant update on table "public"."questions" to "service_role";

grant delete on table "public"."responses" to "anon";

grant insert on table "public"."responses" to "anon";

grant references on table "public"."responses" to "anon";

grant select on table "public"."responses" to "anon";

grant trigger on table "public"."responses" to "anon";

grant truncate on table "public"."responses" to "anon";

grant update on table "public"."responses" to "anon";

grant delete on table "public"."responses" to "authenticated";

grant insert on table "public"."responses" to "authenticated";

grant references on table "public"."responses" to "authenticated";

grant select on table "public"."responses" to "authenticated";

grant trigger on table "public"."responses" to "authenticated";

grant truncate on table "public"."responses" to "authenticated";

grant update on table "public"."responses" to "authenticated";

grant delete on table "public"."responses" to "service_role";

grant insert on table "public"."responses" to "service_role";

grant references on table "public"."responses" to "service_role";

grant select on table "public"."responses" to "service_role";

grant trigger on table "public"."responses" to "service_role";

grant truncate on table "public"."responses" to "service_role";

grant update on table "public"."responses" to "service_role";

grant delete on table "public"."social_items" to "anon";

grant insert on table "public"."social_items" to "anon";

grant references on table "public"."social_items" to "anon";

grant select on table "public"."social_items" to "anon";

grant trigger on table "public"."social_items" to "anon";

grant truncate on table "public"."social_items" to "anon";

grant update on table "public"."social_items" to "anon";

grant delete on table "public"."social_items" to "authenticated";

grant insert on table "public"."social_items" to "authenticated";

grant references on table "public"."social_items" to "authenticated";

grant select on table "public"."social_items" to "authenticated";

grant trigger on table "public"."social_items" to "authenticated";

grant truncate on table "public"."social_items" to "authenticated";

grant update on table "public"."social_items" to "authenticated";

grant delete on table "public"."social_items" to "service_role";

grant insert on table "public"."social_items" to "service_role";

grant references on table "public"."social_items" to "service_role";

grant select on table "public"."social_items" to "service_role";

grant trigger on table "public"."social_items" to "service_role";

grant truncate on table "public"."social_items" to "service_role";

grant update on table "public"."social_items" to "service_role";

grant delete on table "public"."social_sections" to "anon";

grant insert on table "public"."social_sections" to "anon";

grant references on table "public"."social_sections" to "anon";

grant select on table "public"."social_sections" to "anon";

grant trigger on table "public"."social_sections" to "anon";

grant truncate on table "public"."social_sections" to "anon";

grant update on table "public"."social_sections" to "anon";

grant delete on table "public"."social_sections" to "authenticated";

grant insert on table "public"."social_sections" to "authenticated";

grant references on table "public"."social_sections" to "authenticated";

grant select on table "public"."social_sections" to "authenticated";

grant trigger on table "public"."social_sections" to "authenticated";

grant truncate on table "public"."social_sections" to "authenticated";

grant update on table "public"."social_sections" to "authenticated";

grant delete on table "public"."social_sections" to "service_role";

grant insert on table "public"."social_sections" to "service_role";

grant references on table "public"."social_sections" to "service_role";

grant select on table "public"."social_sections" to "service_role";

grant trigger on table "public"."social_sections" to "service_role";

grant truncate on table "public"."social_sections" to "service_role";

grant update on table "public"."social_sections" to "service_role";

grant delete on table "public"."superadmin_emails" to "anon";

grant insert on table "public"."superadmin_emails" to "anon";

grant references on table "public"."superadmin_emails" to "anon";

grant select on table "public"."superadmin_emails" to "anon";

grant trigger on table "public"."superadmin_emails" to "anon";

grant truncate on table "public"."superadmin_emails" to "anon";

grant update on table "public"."superadmin_emails" to "anon";

grant delete on table "public"."superadmin_emails" to "authenticated";

grant insert on table "public"."superadmin_emails" to "authenticated";

grant references on table "public"."superadmin_emails" to "authenticated";

grant select on table "public"."superadmin_emails" to "authenticated";

grant trigger on table "public"."superadmin_emails" to "authenticated";

grant truncate on table "public"."superadmin_emails" to "authenticated";

grant update on table "public"."superadmin_emails" to "authenticated";

grant delete on table "public"."superadmin_emails" to "service_role";

grant insert on table "public"."superadmin_emails" to "service_role";

grant references on table "public"."superadmin_emails" to "service_role";

grant select on table "public"."superadmin_emails" to "service_role";

grant trigger on table "public"."superadmin_emails" to "service_role";

grant truncate on table "public"."superadmin_emails" to "service_role";

grant update on table "public"."superadmin_emails" to "service_role";

grant delete on table "public"."user_roles" to "anon";

grant insert on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "anon";

grant select on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant update on table "public"."user_roles" to "anon";

grant delete on table "public"."user_roles" to "authenticated";

grant insert on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "authenticated";

grant select on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant update on table "public"."user_roles" to "authenticated";

grant delete on table "public"."user_roles" to "service_role";

grant insert on table "public"."user_roles" to "service_role";

grant references on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant update on table "public"."user_roles" to "service_role";


  create policy "Allow anonymous inserts on answers"
  on "public"."answers"
  as permissive
  for insert
  to anon
with check (true);



  create policy "answers_superadmin_all"
  on "public"."answers"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))));



  create policy "event_admins_read"
  on "public"."event_admins"
  as permissive
  for select
  to authenticated
using (((user_id = auth.uid()) OR public.is_superadmin()));



  create policy "event_admins_write"
  on "public"."event_admins"
  as permissive
  for all
  to authenticated
using (public.is_superadmin())
with check (public.is_superadmin());



  create policy "events_delete_superadmin_only"
  on "public"."events"
  as permissive
  for delete
  to authenticated
using (public.is_superadmin());



  create policy "events_insert_admin_or_superadmin"
  on "public"."events"
  as permissive
  for insert
  to authenticated
with check ((public.is_superadmin() OR (EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role = 'admin'::public.app_role))))));



  create policy "events_select_assigned_or_superadmin"
  on "public"."events"
  as permissive
  for select
  to authenticated
using (public.can_manage_event(id));



  create policy "events_superadmin_all"
  on "public"."events"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))));



  create policy "events_update_assigned_or_superadmin"
  on "public"."events"
  as permissive
  for update
  to authenticated
using (public.can_manage_event(id))
with check (public.can_manage_event(id));



  create policy "allow_public_view_quest"
  on "public"."quest"
  as permissive
  for select
  to public
using (true);



  create policy "quest_superadmin_all"
  on "public"."quest"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))));



  create policy "Allow public read on question_options"
  on "public"."question_options"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "question_options_superadmin_all"
  on "public"."question_options"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))));



  create policy "Allow public read on questions"
  on "public"."questions"
  as permissive
  for select
  to anon
using ((is_active = true));



  create policy "questions_manage_assigned_or_superadmin"
  on "public"."questions"
  as permissive
  for all
  to authenticated
using (public.can_manage_event(event_id))
with check (public.can_manage_event(event_id));



  create policy "Allow anonymous inserts on responses"
  on "public"."responses"
  as permissive
  for insert
  to anon
with check (true);



  create policy "responses_superadmin_all"
  on "public"."responses"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))));



  create policy "responses_view_assigned_or_superadmin"
  on "public"."responses"
  as permissive
  for select
  to authenticated
using (public.can_manage_event(event_id));



  create policy "superadmin_emails_superadmin_all"
  on "public"."superadmin_emails"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_roles ur
  WHERE ((ur.user_id = auth.uid()) AND ((ur.role)::text = 'superadmin'::text)))));



  create policy "user_roles_read"
  on "public"."user_roles"
  as permissive
  for select
  to authenticated
using (((user_id = auth.uid()) OR public.is_superadmin()));



  create policy "user_roles_write"
  on "public"."user_roles"
  as permissive
  for all
  to authenticated
using (public.is_superadmin())
with check (public.is_superadmin());


CREATE TRIGGER trg_enforce_answer_event BEFORE INSERT OR UPDATE ON public.answers FOR EACH ROW EXECUTE FUNCTION public.enforce_answer_event_match();

CREATE TRIGGER trg_enforce_response_event BEFORE INSERT OR UPDATE ON public.answers FOR EACH ROW EXECUTE FUNCTION public.enforce_response_event_match();

CREATE TRIGGER trg_validate_booth_completion_event_match BEFORE INSERT OR UPDATE ON public.booth_completions FOR EACH ROW EXECUTE FUNCTION public.validate_booth_completion_event_match();

CREATE TRIGGER trg_assign_initial_role AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.assign_initial_role();


