apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: psd
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: psd
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: psd
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-form
  namespace: psd
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-service
  namespace: psd
spec:
  replicas: 1
